### ISSUE TITLE
docs: track page visits using google analytics

### ISSUE THREAD

**Issue by mgenov** [clouway/docs.clouway.com#13]
To have visibility of page visits it would be valuable they to be tracked using Google Analytics.

GDPR  Notes:
Use Anonymous option of GA

**Comment by FeNoMeNa** [comment]
We will need a tracking id for `docs.clouway.com`

**Comment by mgenov** [comment]
ok, will issue one in a few minutes.

**Comment by mgenov** [comment]
The tracking id of docs.clouway.com is: UA-85799539-4

**Comment by mgenov** [comment]
This is the gtag code:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-85799539-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-85799539-4');
</script>

```

**Comment by FeNoMeNa** [comment]
There is a useful gatsby plugin.

**Comment by mgenov** [comment]
Yes, it could be used. We would like to track simple things in the doc site: Overall page visits and particular page visits.
