### ISSUE TITLE
docs: think about better priority logic 

### ISSUE THREAD

**Issue by FeNoMeNa** [clouway/docs.clouway.com#29]
We should think about a way to improve the "priority" behavior for the pages. The main purpose of the priority field is for organization of the sidebar menu. But what about if you want to insert a page between two other pages with consecutive priorities.

**Comment by mgenov** [comment]
A large number of ranges between pages could be used: A(100) - B(200) - C(300), so if you want to move page between 2 other pages then 

105 or 120 or 230 or 350 could be used to be move page in a proper place.

**Comment by FeNoMeNa** [comment]
Okay, for now I'll close the issue.
