### ISSUE TITLE
docs/mobile: menu not visible in mobile version

### ISSUE THREAD

**Issue by mgenov** [clouway/docs.clouway.com#4]
The left side menu is not visible on the mobile version:

![image](https://user-images.githubusercontent.com/209223/61376670-48280600-a8aa-11e9-8b61-6cc2987f56af.png)

![image](https://user-images.githubusercontent.com/209223/61376860-b40a6e80-a8aa-11e9-9cdd-1a30e7ff6d13.png)

A similar issue was encountered in other parts and it was solved by adding language token as a parameter.

**Comment by IvelinYR** [comment]
@mgenov  I can't be an assignee to this issue.
