### ISSUE TITLE
docs: clear chosen section on page refresh 

### ISSUE THREAD

**Issue by GrishaAngelov** [clouway/docs.clouway.com#52]
When we select given section from the menu for the page and hit refresh then is visualized the start of the page and not the selected section.

![video](https://user-images.githubusercontent.com/1625243/62189948-ecb14a00-b378-11e9-99bd-c292310c2411.gif)

**Comment by FeNoMeNa** [comment]
Strange... this fix does not work on production (gatsby build). Take a look at https://docs.clouway.com/

**Comment by GrishaAngelov** [comment]
The URL is rewritten and we lost the needed information ...

![video](https://user-images.githubusercontent.com/1625243/62208532-df5b8600-b39f-11e9-865a-642b46663a1f.gif)
