### ISSUE TITLE
docs: switch between languages

### ISSUE THREAD

**Issue by mgenov** [clouway/docs.clouway.com#7]
Users should be able to switch between languages to be able to select the proper language of the documentation.

The language selection either could be implemented like facebook one in the page footer:
![image](https://user-images.githubusercontent.com/209223/61427297-4439c980-a926-11e9-8cd4-1fc7e718b59c.png)

Or by using dropdown like menu:

![image](https://media.giphy.com/media/l0MYPpXVh2Yv3dGms/giphy.gif)

**Comment by FeNoMeNa** [comment]
What i18n library will be used?

**Comment by mgenov** [comment]
No concrete library was selected. Currently, the only integrated thing is gatsby-plugin-i18n which re-writes the URL rules to the proper markdown pages (english and bulgarian). 

Regarding: https://www.gatsbyjs.org/docs/localization-i18n/ the suggested library is https://github.com/i18next/react-i18next/ but if there are other ideas they could be considered.

**Comment by FeNoMeNa** [comment]
public-portal uses react-i18next, maybe is a good choice

**Comment by mgenov** [comment]
Sounds good.
